---
title: "Visullization"
author: "Benson Kenduiywo"
date: "12/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Visualize the results

First display the quality measures for different models and data treatment.

```{r viz1, message=FALSE}
library(ggplot2)
#R2
tt <- x[, c("group", "model","r2")]
fig.r2 <- ggplot(aes(x=model, y=group, fill=r2), data=tt)
fig.r2 <- fig.r2 + geom_tile() + scale_fill_gradient2(low="#D7191C", mid="white", high="#2C7BB6") + 
  #   geom_text(aes(label=stars, color=value), size=8) + scale_colour_gradient(low="grey30", high="white", guide="none") +
  geom_text(aes(label=round(r2,2)), color="black", size=5) + 
  labs(y=NULL, x=NULL, fill=expression(R^2)) + 
  theme_bw() + theme(axis.text=element_text(size=13,face="bold"),legend.text=element_text(size=13))
x11()
fig.r2
#RMSE
tt <- x[, c("group", "model","RMSE")]
fig.rmse <- ggplot(aes(x=model, y=group, fill=RMSE), data=tt)
fig.rmse <- fig.rmse + geom_tile() + scale_fill_gradient2(low="#D7191C", mid="white", high="#2C7BB6") + 
  geom_text(aes(label=round(RMSE,2)), color="black", size=5) + 
  labs(y=NULL, x=NULL, fill="RMSE") + 
  theme_bw() + theme(axis.text=element_text(size=13,face="bold"),legend.text=element_text(size=13))
x11()
fig.rmse
library(ggpubr)
ggarrange(fig.r2, fig.rmse, labels = c("(a)", "(b)"),
          ncol = 1, nrow = 2, widths = c(0.5, 0.5,0.5,0.5))
```

Display the welfare of the farmer based on different data treatments and regression models.


```{r viz2, message=FALSE}
library(ggplot2)
library(reshape2)
a <- names(x)
b <- c("r2","RMSE","intercept","slope")
tt <- x[,!a %in% b]
tt <- melt(tt, id=c("group", "model")) 
tt$variable = as.integer(gsub("mqs","",tt$variable))
x11()
ggplot() + 
  geom_point(data = tt, aes(y = value, x = group, size = variable, color = model)) +
  scale_y_continuous(breaks = seq(0, 16, by = 4)) +
  scale_color_manual(values=c('red', 'green', 'blue', 'magenta')) +
  scale_size_continuous(breaks=as.integer(trigs)) +
  labs(x="Data", y="Insurance benefit ($)") + 
  theme_bw() +
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=11,face="bold"), legend.text=element_text(size=11)) +
  guides(color=guide_legend("Model"), size=guide_legend("Trigger"))
  
```
