---
title: "IBLI visualisation"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---
## load packages
```{r packages, message=FALSE}
library(ggplot2)
library(reshape2)
```

## read data

```{r v1}
rm(list = ls(all=TRUE))
x <- readRDS("reg_RIB.rds")
z <- readRDS("perfect.rds")
```

Visualize all the variables (RIB, model, triggers and remote sensing indices).

```{r v2}
tt <- x[, c("group", "model","mqs10.3", "mqs12.6", "mqs13.9", "mqs15.8", "mqs17.6", "mqs23", "mqs27.6", "mqs41.5" )]
tt <- melt(tt, id=c("group", "model")) 
tt$variable = as.double(gsub("mqs","",tt$variable))
trigs <- unique(tt$variable)

ggplot() + 
  geom_point(data = tt, aes(y = value, x = group, size = variable, color = model)) +
  scale_y_continuous(breaks = seq(-3.5, 0.7, by = 0.5)) + #seq(0, 0.75, by = 0.1)
  scale_color_manual(values=c('red', 'green', 'blue', 'magenta')) +
  #scale_size_continuous(breaks=trigs) +
  labs(x="Remote sensing index", y="RIB") + 
  theme_bw() +
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=11,face="bold"), legend.text=element_text(size=11)) +
  guides(color=guide_legend("Model"), size=guide_legend("Trigger"))

```

The best threshold is 80%, or mqs23. Let's first just look at that one

```{r v3}
z
apply(x[, 7:ncol(x)], 2, max)
```

```{r v4}
tv <- "23"
tvar <- paste0("mqs", tv)
vars <- c("group", "model", "r2", tvar)
d <- x[, vars]
colnames(d) <- gsub(tvar, "RIB", colnames(d))
head(d)
```
barplots with all parameters at trigger=23%.

```{r v5}

par(mfrow=c(2, 2), mar=c(4.5, 4.2, 1.8, 1)) #c(bottom, left, top, right)
boxplot(r2~model, data=d, ylab = expression(R^2), xlab="Model")
boxplot(RIB~model, data=d, xlab="Model")
boxplot(r2~group, data=d, ylab = expression(R^2), xlab="Remote sensing index")
boxplot(RIB~group, data=d, xlab="Remote sensing index")

```


```{r v6}
group.which.max <- function(var) {
  g <- lapply(split(d, d$group), function(i) i[which.max(i[[var]]), ]) 
  do.call(rbind, g)
}
s1 <- group.which.max("r2")
s2 <- group.which.max("RIB")
s <- cbind(s1[,1:3], s2[,c(2,4)])
rownames(s) <- NULL
s
s[order(s$r2), ]
plot(s$r2, s$RIB)
```

Plot RIB against R$^2$ under mortality trigger of 23%.

```{r v7}
<<<<<<< HEAD
x11()
#par(mar=c(7, 7, 7, 7)) #c(bottom, left, top, right)
#plot(d[,3:4], pch=20, col="red", xlab = expression(R^2)) #, xlim=c(0,1), ylim=c(0,1))
temp <- d
temp$model[temp$model=="seg"] <- 'sm'
ggplot() + 
  geom_point(data = temp, aes(y = RIB, x = r2, color = model)) +
  scale_color_manual(values=c('magenta', 'blue', 'green', 'red')) +
  labs(x=expression(R^2), y="RIB") + 
  theme_bw()+
  theme(plot.margin = unit(c(4,2,2,2), "cm"))

=======

plot(d[,3:4], pch=20, col="red", xlab = expression(R^2)) #, xlim=c(0,1), ylim=c(0,1))
>>>>>>> 6d46b0f400b204529630bd8e0800523086b43e03
```

Plot RIB against R$^2$ consider all mortality triggers: 10.3%, 12.6%, 13.9%, 15.8%, 17.6%, 23.0%, 27.6%, and 41.5%.

```{r v8}
tt <- x[, c("group", "model","r2","mqs10.3", "mqs12.6", "mqs13.9", "mqs15.8", "mqs17.6", "mqs23", "mqs27.6", "mqs41.5" )]
trig_plots <- function(models, label){
  d <- tt[tt$model==models,]
  plot(mqs10.3~r2, data=d, pch=20, col="black", ylab="RIB", xlab = expression(R^2), ylim=c(min(d$mqs10.3)-0.1, max(d$mqs17.6)+0.1), main=label, cex=0.9, cex.main=1.2, cex.lab=1.2) #yaxt="none"
  #axis(2, seq(-3.5, 1, by = 0.5),las=2)
  points(mqs12.6~r2, data=tt, pch=20, col="blue")
  points(mqs13.9~r2, data=tt, pch=20, col="red")
  points(mqs15.8~r2, data=tt, pch=20, col="green")
  points(mqs17.6~r2, data=tt, pch=20, col="magenta")
  points(mqs23~r2, data=tt, pch=20,   col="cyan")
  points(mqs27.6~r2, data=tt, pch=20, col="brown")
  points(mqs41.5~r2, data=tt, pch=20, col="yellow")
  #legend("bottomleft", c("10.3%", "12.6%", "13.9%", "15.8%", "17.6%", "23.0%", "27.6%", "41.5%"), pch=20, col=c("black", "blue", "red", "green", "magenta", "cyan", "brown", "yellow"), title = "Trigger", bty = "n")
}

par(mfrow=c(2, 2), mar=c(4.5, 4.2, 1.8, 1))
trig_plots("lm", "(a)")
trig_plots("lm0", "(b)")
trig_plots("lm5", "(c)")
trig_plots("seg", "(d)")

legend("bottomleft", c("10.3%", "12.6%", "13.9%", "15.8%", "17.6%", "23.0%", "27.6%", "41.5%"), pch=20, col=c("black", "blue", "red", "green", "magenta", "cyan", "brown", "yellow"), title = "Trigger", bty = "n")

```

